### ISSUE TITLE
No Module named 'airway_cli'

### ISSUE THREAD

**Issue by id-b3** [LiquidFun/Airway#13]
When trying to use your module I get this error:

`Traceback (most recent call last):  
  File "C:\Users\_\miniconda3\envs\airwaylabeling\lib\runpy.py", line 194, in _run_module_as_main  
    return _run_code(code, main_globals, None,  
  File "C:\Users\_\miniconda3\envs\airwaylabeling\lib\runpy.py", line 87, in _run_code  
    exec(code, run_globals)  
  File "C:\Users\_\miniconda3\envs\airwaylabeling\Scripts\airway.exe\__main__.py", line 4, in <module>  
ModuleNotFoundError: No module named 'airway_cli'`

I installed the package using pip. Can you please advise on what to do?

**Comment by LiquidFun** [comment]
Thank you for letting me know! Not sure how I missed it, I'll fix it this weekend. For now you can clone the repository and use the `airway_cli.py` script directly.

**Comment by LiquidFun** [comment]
Should be fixed in release 0.2.1 (which is now installable via pip). Feel free to let me know if there are other issues.
