### ISSUE TITLE
Running airway with own 'raw_airway' using dicom data

### ISSUE THREAD

**Issue by RobGhys** [LiquidFun/Airway#17]
Thanks for sharing this project. 
We are trying to reproduce some results with our own dicom data (see Documents/dicompath), and wish to use the raw_airway DATA.
When updating the defaults.yaml local path to a folder that contains the data, we try to run the pipeline using: 
airway stages 1

**Here is the output of the command**
(base) root:~/Documents/GitHub/Airway$ airway stages 1
[09:17:03] Running Airway
           Using up to 8 workers
           Using /home/robin/Documents/dicompath as data path
           Stage processing order: 01
           
Traceback (most recent call last):
  File "/home/robin/anaconda3/bin/airway", line 33, in <module>
    sys.exit(load_entry_point('airway==0.2.3', 'console_scripts', 'airway')())
  File "/home/robin/anaconda3/lib/python3.10/site-packages/airway-0.2.3-py3.10.egg/airway/cli/cli.py", line 35, in main
    handle_args()
  File "/home/robin/anaconda3/lib/python3.10/site-packages/airway-0.2.3-py3.10.egg/airway/cli/cli.py", line 29, in handle_args
    args.handle_args(args)
  File "/home/robin/anaconda3/lib/python3.10/site-packages/airway-0.2.3-py3.10.egg/airway/cli/base.py", line 44, in _handle_args_wrapper
    self.handle_args(args)
  File "/home/robin/anaconda3/lib/python3.10/site-packages/airway-0.2.3-py3.10.egg/airway/cli/stages.py", line 191, in handle_args
    self.stage(curr_stage_name, **self.stage_configs[curr_stage_name], **vars(args))
  File "/home/robin/anaconda3/lib/python3.10/site-packages/airway-0.2.3-py3.10.egg/airway/cli/stages.py", line 281, in stage
    self.concurrent_executor(subprocess_args, script_module, workers, tqdm_prefix=tqdm_prefix, verbose=verbose)
  File "/home/robin/anaconda3/lib/python3.10/site-packages/airway-0.2.3-py3.10.egg/airway/cli/base.py", line 101, in concurrent_executor
    stage_name = Path(subprocesses[0][3]).parent.name
IndexError: list index out of range

**Comment by LiquidFun** [comment]
What does your defaults.yaml look like? And what is the file structure of the raw_airway folder?

**Comment by tq-quan** [comment]
Hello, have you successfully reproduced the results on your data?
