### ISSUE TITLE
the error happended to Processing stage-03

### ISSUE THREAD

**Issue by tq-quan** [LiquidFun/Airway#20]
Hello, dear developer, when I ran airway stages 3 on my data, there was always an error, do you konw how to solve it?
[18:52:15] Processing stage-03
           
[18:52:51] Output for Process 1/1 (Patient pat01)
           STDOUT:
           Model loaded with shape (462, 227, 385)
           Average starting coordinate: [  1. 176.  58.]
           Closest starting coordinate to average: [1, 176, 58]
           Writing distance to coords with shape: (514,)
           distance_mask (462, 227, 385)
           
           
           STDERR:
           Traceback (most recent call last):
             File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
               return _run_code(code, main_globals, None,
             File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
               exec(code, run_globals)
             File "/opt/conda/lib/python3.8/site-packages/airway/tree_extraction/bfs_distance_method.py", line 154, in <module>
               main()
             File "/opt/conda/lib/python3.8/site-packages/airway/tree_extraction/bfs_distance_method.py", line 150, in main
               distance_mask = get_distance_in_model_from_skeleton(visited)
             File "/opt/conda/lib/python3.8/site-packages/airway/tree_extraction/bfs_distance_method.py", line 135, in get_distance_in_model_from_skeleton
               if model[adj] == 1:
           IndexError: index 462 is out of bounds for axis 0 with size 462

**Comment by LiquidFun** [comment]
Hey, I'm currently on holiday. I'll reply to you on May 5-ish.

My initial guess is that your model is not continuous, but I'm not sure. If
you are allowed to send the model, then send it to me (my first name @
gmail.com), I'll take a look.
